name: build
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install project Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deployment Setup
        run: rm -rf .gitignore

      - name: Deployment
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "dist"
          SINGLE_COMMIT: true
          PRESERVE: true
